SELECT * FROM SPACEXTBL limit 5;

SELECT COUNT(DISTINCT launch_site) FROM SPACEXTBL;

SELECT DISTINCT launch_site FROM SPACEXTBL;

SELECT COUNT(*) FROM SPACEXTBL
    WHERE launch_site LIKE 'CCA%'
    limit 5;
    
SELECT SUM(PAYLOAD_MASS__KG_) FROM SPACEXTBL
    WHERE CUSTOMER = 'NASA (CRS)';
    
SELECT AVG(PAYLOAD_MASS__KG_) FROM SPACEXTBL
    WHERE BOOSTER_VERSION = 'F9 v1.1';
    
SELECT MIN(DATE) FROM SPACEXTBL
    WHERE LANDING__OUTCOME = 'Success (ground pad)';
    
SELECT BOOSTER_VERSION FROM SPACEXTBL
    WHERE LANDING__OUTCOME = 'Success (drone ship)'
    AND (PAYLOAD_MASS__KG_ BETWEEN 4000 AND 6000);
    
SELECT MISSION_OUTCOME, COUNT(*) FROM SPACEXTBL
    GROUP BY MISSION_OUTCOME;
    
SELECT BOOSTER_VERSION, PAYLOAD_MASS__KG_ FROM SPACEXTBL
    WHERE PAYLOAD_MASS__KG_ = (SELECT MAX(PAYLOAD_MASS__KG_) FROM SPACEXTBL);
    
SELECT BOOSTER_VERSION, LAUNCH_SITE, LANDING__OUTCOME FROM SPACEXTBL
    where (LANDING__OUTCOME like 'Failure (drone ship)')
    and (DATE like '2015%');
    
SELECT LANDING__OUTCOME, COUNT(LANDING__OUTCOME) FROM SPACEXTBL
    WHERE DATE BETWEEN '2010-06-04' AND '2017-03-20'
    GROUP BY LANDING__OUTCOME
    ORDER BY COUNT(LANDING__OUTCOME) DESC;